# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path


name: Publish package to the Maven Central Repository and GitHub Packages
on:
  push:
    branches: 
      - 'master'
      - 'feature/IntegratingWithGithubAction'
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name : checking folder
        run : ls
      - name : github workspace
        env:
          PATH_POM: JMapper Framework
        run : cd ${{ github.workspace }}/${{PATH_POM}}/  
      - name : checking folder
        run : ls
      - name : path
        run : pwd
      - name: Publish to the Maven Central Repository
        run: mvn clean install -X
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish to GitHub Packages
        run: mvn clean install -X
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
